name = "AOC2021"
uuid = "8074e4e6-93b1-4cb4-9423-4aa0b28e125c"
authors = ["Brynjar Sm√°ri Bjarnason <binni@binnisb.com> and contributors"]
version = "0.1.0"

[deps]
Graphs = "86223c79-3864-5bf0-83f7-82e725a168b6"
Memoize = "c03570c3-d221-55d1-a50c-7939bbd78826"
MetaGraphsNext = "fa8bd995-216d-47f1-8a91-f3b68fbeb377"

[compat]
julia = "1.6"
